import { createSale, deleteSale } from "../data.js";
import { centsFromInput, escapeHtml, formatDate, formatTimestamp, moneyFromCents } from "../utils.js";

export function renderVendas(container, data, uid, helpers) {
  const options = data.estoque.map(p=>`<option value="${p.id}">${escapeHtml(p.produto)} — ${moneyFromCents(p.precoUnitarioCentavos)} (disp. ${p.quantidade})</option>`).join("");
  container.innerHTML = `
    <div class="page-head"><div><h2>Vendas</h2><p>Registre vendas e faça o controle automático do estoque.</p></div></div>
    <form class="card form-card" id="sale-form">
      ${data.estoque.length ? `<div class="form-grid"><div class="field"><label for="sale-customer">Nome cliente</label><input id="sale-customer" placeholder="Opcional"></div><div class="field"><label for="sale-date">Data *</label><input id="sale-date" type="date" required></div></div>
      <div style="margin-top:22px"><div class="section-title">Produtos</div><div class="sale-lines" id="sale-lines"></div><button type="button" class="btn btn-ghost btn-small" id="add-sale-line">+ Adicionar produto</button></div>
      <div class="form-grid" style="margin-top:18px"><div class="field"><label for="sale-payment">Forma de pagamento *</label><select id="sale-payment"><option value="">Selecione</option><option value="Pix">Pix</option>
<option value="Dinheiro">Dinheiro</option>
<option value="Cartão">Cartão</option></select></div><div class="field"><label>Total da venda</label><div class="total-box"><span>Total</span><strong id="sale-total">R$ 0,00</strong></div></div><div class="field hidden" id="cash-field"><label for="cash-received">Valor recebido *</label><input id="cash-received" type="number" min="0" step="0.01" placeholder="0,00"><div class="total-box"><span>Troco</span><strong id="cash-change">R$ 0,00</strong></div></div></div>
      <label class="confirm-line"><input id="sale-confirm" type="checkbox"> <span>Confirmo que os produtos, quantidades e forma de pagamento estão corretos.</span></label>
      <div class="form-actions"><button class="btn btn-primary" type="submit">Registrar venda</button></div>` : `<div class="empty"><strong>Cadastre produtos no estoque primeiro.</strong>As opções de venda vêm do estoque atual.</div>`}
    </form>
    <div class="card table-card">${data.vendas.length ? `<div class="table-scroll"><table><thead><tr><th>Cliente</th><th>Produtos / quantidades</th><th>Total</th><th>Pagamento</th><th>Data</th><th>Hora</th><th>Excluir</th></tr></thead><tbody>${data.vendas.map(v=>`<tr><td>${escapeHtml(v.cliente)}</td><td>${v.produtos.map(p=>`${escapeHtml(p.produto)} × ${p.quantidade}`).join("<br>")}</td><td class="money">${moneyFromCents(v.totalCentavos)}</td><td>${escapeHtml(v.formaPagamento)}${v.formaPagamento === "Dinheiro" ? `<br><span class="small-muted">Recebido ${moneyFromCents(v.valorRecebidoCentavos)} · Troco ${moneyFromCents(v.trocoCentavos)}</span>` : ""}</td><td>${formatDate(v.data)}</td><td>${formatTimestamp(v.horarioRegistro)}</td><td><button class="btn btn-danger btn-small delete-sale" data-id="${v.id}">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : `<div class="empty"><strong>Nenhuma venda registrada.</strong>As vendas concluídas aparecerão aqui.</div>`}</div>`;
  if(!data.estoque.length) return;
  const dateEl=container.querySelector("#sale-date");
  const lines=container.querySelector("#sale-lines"); const totalEl=container.querySelector("#sale-total"); const payment=container.querySelector("#sale-payment"); const cashField=container.querySelector("#cash-field"); const cash=container.querySelector("#cash-received"); const change=container.querySelector("#cash-change");
  const addLine = (selected="") => { const div=document.createElement("div"); div.className="sale-line"; div.innerHTML=`<div class="field"><label>Produto</label><select class="line-product"><option value="">Selecione</option>${options}</select></div><div class="field"><label>Qtd.</label><input class="line-qty" type="number" min="1" step="1" value="1"></div><div class="line-subtotal">R$ 0,00</div><button type="button" class="icon-btn remove-line" aria-label="Remover produto">×</button>`; lines.appendChild(div); div.querySelector(".line-product").value=selected; div.querySelectorAll("select,input").forEach(el=>el.addEventListener("input",update)); div.querySelector(".remove-line").addEventListener("click",()=>{div.remove();update();}); update(); };
  const update = () => { let total=0; lines.querySelectorAll(".sale-line").forEach(line=>{const id=line.querySelector(".line-product").value; const p=data.estoque.find(x=>x.id===id); const q=Number(line.querySelector(".line-qty").value||0); const subtotal=p?q*Number(p.precoUnitarioCentavos):0; line.querySelector(".line-subtotal").textContent=moneyFromCents(subtotal); total+=subtotal;}); totalEl.textContent=moneyFromCents(total); const received=centsFromInput(cash?.value||0); change.textContent=moneyFromCents(Number.isFinite(received)?Math.max(0,received-total):0); };
  addLine(); container.querySelector("#add-sale-line").addEventListener("click",()=>addLine()); payment.addEventListener("change",()=>{cashField.classList.toggle("hidden",payment.value!=="Dinheiro");update();}); cash.addEventListener("input",update);
  container.querySelector("#sale-form").addEventListener("submit",async e=>{
    e.preventDefault();
    const rows=[...lines.querySelectorAll(".sale-line")]; const items=[]; const seen=new Set();
    for(const row of rows){const id=row.querySelector(".line-product").value; const qty=Number(row.querySelector(".line-qty").value); if(!id||!Number.isInteger(qty)||qty<=0) return helpers.toast("Preencha produto e quantidade corretamente.","error"); if(seen.has(id)) return helpers.toast("Não repita o mesmo produto na mesma venda.","error"); seen.add(id); const p=data.estoque.find(x=>x.id===id); if(!p) return helpers.toast("Produto não encontrado no estoque.","error"); items.push({produtoId:p.id,produto:p.produto,quantidade:qty,precoUnitarioCentavos:Number(p.precoUnitarioCentavos),subtotalCentavos:qty*Number(p.precoUnitarioCentavos)});}
    if(!items.length) return helpers.toast("Adicione pelo menos um produto.","error");
    const total=items.reduce((s,i)=>s+i.subtotalCentavos,0); const forma=payment.value; const recebido=forma==="Dinheiro"?centsFromInput(cash.value):total; const troco=forma==="Dinheiro"?recebido-total:0;
    if(!forma) return helpers.toast("Selecione a forma de pagamento.","error"); if(forma==="Dinheiro" && (!Number.isFinite(recebido)||recebido<total)) return helpers.toast("O valor recebido deve ser igual ou maior que o total.","error"); if(!container.querySelector("#sale-confirm").checked) return helpers.toast("Confirme os dados da venda antes de registrar.","error"); if(!dateEl.value) return helpers.toast("Escolha a data da venda.","error");
    try { await createSale(uid,{cliente:container.querySelector("#sale-customer").value.trim()||"Não informado",produtos:items,totalCentavos:total,formaPagamento:forma,valorRecebidoCentavos:recebido,trocoCentavos:troco,data:dateEl.value}); helpers.toast("Venda registrada.","success"); await helpers.refresh(); } catch(err){helpers.toast(err.message,"error");}
  });
  container.querySelectorAll(".delete-sale").forEach(btn=>btn.addEventListener("click",async()=>{if(!confirm("Tem certeza que deseja excluir esta venda? Os produtos vendidos serão devolvidos ao estoque."))return; try{await deleteSale(uid,btn.dataset.id);helpers.toast("Venda excluída e estoque restaurado.","success");await helpers.refresh();}catch(err){helpers.toast(err.message,"error");}}));
}
